name: chess_bros_trading

services:
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  api_test:
    build:
      context: ./api_test
    env_file:
      - ./api_test/.env

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      BROWSER: "none"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
